### ISSUE TITLE
Admin panel : Unable to approve claim

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#295]
When approving a claim I get the following error msg 

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/e078b0a2-aefa-4ad0-886b-f2106c18630a)

**Comment by karelstriegel** [comment]
When going back to the main overview the pending claim is gone
![image](https://user-images.githubusercontent.com/6882032/40055204-67299492-5847-11e8-86e8-257ff0916309.png)

and in the request detail the request is set to "claimed"

![image](https://user-images.githubusercontent.com/6882032/40055220-76ba8128-5847-11e8-849f-84bb8f3e8a1c.png)

The funds also have been transferred

![image](https://user-images.githubusercontent.com/6882032/40055262-9c5a91c0-5847-11e8-9234-dadc59b98826.png)

**Comment by Qkyrie** [comment]
Fixed in branch 192-reapproving-claims in azrael

**Comment by karelstriegel** [comment]
@davyvanroy 
**Update**
Got a new error when trying to perform a new claim (different request), and after I restarted dev-web (wanted the latest code)

This is the error msg
![image](https://user-images.githubusercontent.com/6882032/40082710-145e23c2-5892-11e8-8176-672fd321ddaa.png)


**important** this time the claim remains and is not resolved
![image](https://user-images.githubusercontent.com/6882032/40082757-3921bd68-5892-11e8-9da5-3dada45467d6.png)


![image](https://user-images.githubusercontent.com/6882032/40082739-27e61fd0-5892-11e8-9cd7-0296339f727f.png)
